name: Ask for Input Workflow

on: [push]

jobs:
  input_job:
    runs-on: ubuntu-latest

    steps:
    - name: Ask for Input
      run: |
        echo "::group::Input Required"
        read -p 'What is your name? ' name
        echo "::endgroup::"
        echo "Hello, $name!"
