name: TEST call with input.

on:
  workflow_dispatch:

jobs:
  input_job:
    runs-on: ubuntu-latest

    steps:
    - name: Ask for Input
      run: |
        echo "What is your name?"
        read name
        echo "Hello, $name!"
